<?php

require_once dirname(__FILE__) . '/../../../../../../../../Projects/anaconda/system/anaconda/src/Map.php';
require_once dirname(__FILE__) . '/../../../../../../../../Projects/anaconda/system/anaconda/src/anaconda/Map.php';

/**
 * Test class for Map.
 * Generated by PHPUnit on 2012-07-23 at 23:17:51.
 */
class MapTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Map
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new \anaconda\Map;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function test() {
    }
}

?>
