<?php

require_once dirname(__FILE__) . '/../../../../../../../../Projects/anaconda/system/anaconda/src/anaconda/Publisher.php';

/**
 * Test class for Publisher.
 * Generated by PHPUnit on 2012-07-23 at 23:17:51.
 */
class PublisherTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Publisher
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Publisher;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
