<?php

require_once dirname(__FILE__) . '/../../../../../../../../Projects/anaconda/system/anaconda/src/anaconda/Tree.php';

/**
 * Test class for Tree.
 * Generated by PHPUnit on 2012-07-23 at 23:17:51.
 */
class TreeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Tree
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Tree;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
