<?php

require_once dirname(__FILE__) . '/../../../../../../../../Projects/anaconda/system/anaconda/src/Vector.php';
require_once dirname(__FILE__) . '/../../../../../../../../Projects/anaconda/system/anaconda/src/anaconda/Vector.php';

/**
 * Test class for Vector.
 * Generated by PHPUnit on 2012-07-23 at 23:17:52.
 */
class VectorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Vector
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new \anaconda\Vector;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function test() {
    }

}

?>
